### ISSUE TITLE
Specify UDP Port? Character Deliniation

### ISSUE THREAD

**Issue by mrtinvan** [Sinclair81/Homebridge-UDP-Sender#2]
Is there any method within the plugin to specify the Port the command needs to be sent to? How about a command deliniation, like I need to send a Carriage Return to execute the command.

**Comment by Sinclair81** [comment]
To specify the port there is an extra variable "port", you can see in the example. I will write it correctly in the manual anyway.
You can take anything as commands to be sent to your device via UDP for ON or OFF. For "Carriage Return" try "\ n" or "\ r \ n".
